#+title: c-llvm-trans.ll
#+author: conao3

[[https://github.com/conao3/c-llvm-trans.ll][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/c-llvm-trans.ll.png]]
[[https://github.com/conao3/c-llvm-trans.ll/blob/master/LICENSE][https://img.shields.io/github/license/conao3/c-llvm-trans.ll.svg?style=flat-square]]
[[https://github.com/conao3/c-llvm-trans.ll/releases][https://img.shields.io/github/tag/conao3/c-llvm-trans.ll.svg?style=flat-square]]
[[https://www.patreon.com/conao3][https://img.shields.io/badge/patreon-become%20a%20patron-orange.svg?logo=patreon&style=flat-square]]
[[https://twitter.com/conao_3][https://img.shields.io/badge/twitter-@conao__3-blue.svg?logo=twitter&style=flat-square]]
[[https://conao3-support.slack.com/join/shared_invite/zt-32da65wtx-MwzsDg8czOrO0wBuHo_tdQ][https://img.shields.io/badge/chat-on_slack-blue.svg?logo=slack&style=flat-square]]

* Overview

A practical collection of LLVM IR (.ll) files generated from C source code using Clang, designed to help developers learn and understand LLVM Intermediate Representation.

The approach of learning LLVM by reading compiler-generated IR is inspired by several excellent resources:
- [[http://www.wilfred.me.uk/blog/2015/02/21/my-first-llvm-compiler/][My First LLVM Compiler]]
- [[https://itchyny.hatenablog.com/entry/2017/02/27/100000][LLVMを始めよう！ 〜 LLVM IRの基礎はclangが教えてくれた・Brainf**kコンパイラを作ってみよう 〜]]

* Getting Started

This repository is intended as a learning resource. Simply browse and read the =.ll= files to explore how C code translates to LLVM IR.

To generate your own =.ll= files from C source:

#+begin_src shell
clang -S -emit-llvm -O0 your_file.c -o your_file.ll
#+end_src

* License

#+begin_example
The MIT License (MIT)
Copyright (c) Naoya Yamashita - https://conao3.com
https://github.com/conao3/c-llvm-trans.ll/blob/master/LICENSE
#+end_example

* Community and Support

Feedback and questions are always welcome. Feel free to open an issue on GitHub or join the [[https://conao3-support.slack.com/join/shared_invite/zt-32da65wtx-MwzsDg8czOrO0wBuHo_tdQ][Slack community]] for discussion.

If you find this project helpful, consider supporting development on [[https://www.patreon.com/conao3][Patreon]].

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
